"use client";

import Image from "next/image";
import { useRef } from "react";
import { motion, useInView } from "framer-motion";
import TickerBar from "@/components/sections/TickerBar";
import CTAButton from "@/components/ui/CTAButton";

const SPRING = { type: "spring" as const, stiffness: 420, damping: 26 };

function FadeIn({
  children,
  delay = 0,
  className = "",
}: {
  children: React.ReactNode;
  delay?: number;
  className?: string;
}) {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true, margin: "-60px" });
  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 24 }}
      animate={inView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1], delay }}
      className={className}
    >
      {children}
    </motion.div>
  );
}

/* ═══════════════════════════════════
   HERO
═══════════════════════════════════ */
function ChargeHero() {
  return (
    <section className="bg-white w-full">
      <div className="max-w-[1440px] mx-auto px-5 lg:px-20 pt-20 lg:pt-[104px] pb-16 lg:pb-[104px] flex flex-col lg:flex-row items-center justify-between gap-10 lg:gap-8">

        {/* Left: headline + body + CTA */}
        <div className="flex flex-col gap-4 lg:w-[531px] shrink-0">
          <motion.h1
            className="text-[64px] md:text-[96px] lg:text-[134px] leading-[0.88] font-black uppercase text-[#004762]"
            style={{ fontFamily: "var(--font-mona-sans)" }}
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.65, ease: [0.22, 1, 0.36, 1] }}
          >
            STAY IN-CHARGE<span className="text-[#00aeef]">.</span>
          </motion.h1>

          <motion.p
            className="text-[16px] lg:text-[18px] text-[#004762] leading-[28px]"
            style={{ fontFamily: "var(--font-instrument-sans)", fontWeight: 400 }}
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1], delay: 0.1 }}
          >
            We solve the Grid Problem and the Range Problem.{" "}
            <br className="hidden lg:block" />
            Our Charging Hubs utilize solar microgrids to ensure 99.9% uptime.
          </motion.p>

          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1], delay: 0.18 }}
          >
            <CTAButton>FIND A CHARGE STATION</CTAButton>
          </motion.div>
        </div>

        {/* Right: EV station image */}
        <motion.div
          className="relative w-full lg:w-[691px] h-[300px] md:h-[400px] lg:h-[481px] rounded-[24px] lg:rounded-[32px] overflow-hidden shrink-0"
          initial={{ opacity: 0, scale: 0.96 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.65, ease: [0.22, 1, 0.36, 1], delay: 0.06 }}
        >
          <Image
            src="/images/charge/ev-station-hero.jpg"
            alt="EV charging station with solar canopy"
            fill
            priority
            className="object-cover object-center"
          />
        </motion.div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════
   DEPIN PARTNER SECTION
═══════════════════════════════════ */
function DepinSection() {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true, margin: "-60px" });

  const features = [
    {
      n: "01",
      tag: "Flexible",
      bullets: ["Stop letting your real estate sit idle. Start earning passive income from every kilowatt dispensed."],
    },
    {
      n: "02",
      tag: "Credible",
      bullets: ["Join 200+ Partners", "99.9% Uptime Guarantee", "Secured payment"],
    },
    {
      n: "03",
      tag: "Rewarding",
      bullets: ["Gain exclusive access to tradable Carbon Credits generated by your node."],
    },
  ];

  return (
    <section ref={ref} className="bg-[#f6f6f6] w-full px-5 lg:px-20 py-16 lg:py-24">
      <div className="max-w-[1440px] mx-auto flex flex-col lg:flex-row gap-8 lg:gap-8 items-start">

        {/* Left column */}
        <div className="flex flex-col gap-10 lg:w-[602px] shrink-0">
          <motion.div
            className="flex flex-col gap-6"
            initial={{ opacity: 0, y: 24 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
          >
            <h2
              className="text-[24px] lg:text-[33px] text-[#004762] leading-[1.15]"
              style={{ fontFamily: "var(--font-cal-sans)" }}
            >
              Join us as partners of our Off-grid Charging Infra.
            </h2>
            <p
              className="text-[16px] lg:text-[18px] text-[#004762] leading-[24px]"
              style={{ fontFamily: "var(--font-instrument-sans)", fontWeight: 400 }}
            >
              Join the Routa Energy DePIN Network. Own a charging node, serve the Routa fleet, and earn real-time revenue from the energy transition.
            </p>
          </motion.div>

          <motion.div
            className="relative w-full h-[260px] md:h-[342px] rounded-[32px] lg:rounded-[40px] overflow-hidden"
            initial={{ opacity: 0, scale: 0.97 }}
            animate={inView ? { opacity: 1, scale: 1 } : {}}
            transition={{ duration: 0.65, ease: [0.22, 1, 0.36, 1], delay: 0.1 }}
          >
            <Image
              src="/images/charge/ev-hub-outdoor.jpg"
              alt="Outdoor EV charging hub with solar canopy"
              fill
              className="object-cover object-bottom"
            />
          </motion.div>
        </div>

        {/* Right column */}
        <div className="flex flex-col gap-2 flex-1 lg:w-[645px] shrink-0 lg:justify-between">

          {/* Featuring row */}
          <motion.div
            className="flex flex-col sm:flex-row gap-2"
            initial={{ opacity: 0, y: 24 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1], delay: 0.08 }}
          >
            <div className="bg-white rounded-[24px] px-10 py-[26px] flex items-center justify-center shrink-0">
              <p
                className="text-[24px] text-[#004762] whitespace-nowrap"
                style={{ fontFamily: "var(--font-cal-sans)" }}
              >
                Featuring
              </p>
            </div>

            {/* OUTSIDE token card */}
            <div className="bg-white rounded-[24px] h-[83px] px-6 flex items-center justify-between flex-1 min-w-0">
              <div className="flex items-center gap-3">
                <div className="relative w-[35px] h-[35px] shrink-0">
                  <Image src="/images/charge/token-ellipse.png" alt="" fill className="object-cover rounded-full" />
                  <Image src="/images/charge/outside-token-avatar.png" alt="OUTSIDE" fill className="object-cover rounded-full" />
                  {/* BNB badge */}
                  <div className="absolute bottom-[-1px] right-[-1px] w-[12px] h-[12px] bg-[#f0b90b] rounded-[4px] border-[1.6px] border-white" />
                </div>
                <div className="flex flex-col gap-1">
                  <p className="text-[16px] font-bold text-[#004762] leading-none" style={{ fontFamily: "var(--font-instrument-sans)", fontWeight: 700 }}>OUTSIDE</p>
                  <div className="flex items-center gap-1.5 text-[12px]" style={{ fontFamily: "var(--font-instrument-sans)" }}>
                    <span className="text-[#004762]">$0.62224</span>
                    <span className="text-[#17b26a]">+83.09%</span>
                  </div>
                </div>
              </div>
              <div className="flex flex-col items-end gap-1">
                <p className="text-[16px] font-semibold text-[#004762]" style={{ fontFamily: "var(--font-instrument-sans)", fontWeight: 600 }}>314.67565</p>
                <p className="text-[12px] text-[#004762]" style={{ fontFamily: "var(--font-instrument-sans)" }}>$505.71</p>
              </div>
            </div>
          </motion.div>

          {/* Feature rows */}
          <div className="flex flex-col gap-2">
            {features.map((f, i) => (
              <motion.div
                key={f.n}
                className="relative bg-white rounded-[16px] px-6 py-4 overflow-hidden flex gap-4 items-start"
                initial={{ opacity: 0, x: 24, y: 8 }}
                animate={inView ? { opacity: 1, x: 0, y: 0 } : {}}
                transition={{ duration: 0.45, ease: [0.22, 1, 0.36, 1], delay: 0.12 + i * 0.08 }}
              >
                {/* Ghost number */}
                <span
                  className="absolute top-0 right-[100px] translate-x-full text-[110px] leading-[1.1] text-[#f6fcff] font-extralight tracking-[-2.2px] select-none pointer-events-none"
                  style={{ fontFamily: "var(--font-mona-sans)", fontWeight: 200 }}
                  aria-hidden="true"
                >
                  {f.n}
                </span>

                {/* Tag pill */}
                <span
                  className="bg-[#f6fcff] text-[#004762] text-[14px] px-4 py-2 rounded-full shrink-0 whitespace-nowrap h-9 flex items-center"
                  style={{ fontFamily: "var(--font-instrument-sans)", fontWeight: 400 }}
                >
                  {f.tag}
                </span>

                {/* Bullet content */}
                <ul
                  className="text-[14px] text-[#004762] leading-[20px] flex-1 min-w-0 list-disc ml-5"
                  style={{ fontFamily: "var(--font-instrument-sans)", fontWeight: 400 }}
                >
                  {f.bullets.map((b) => (
                    <li key={b}>{b}</li>
                  ))}
                </ul>
              </motion.div>
            ))}
          </div>

          {/* Bottom CTA card */}
          <motion.div
            className="bg-white rounded-[24px] p-8 lg:p-10 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6"
            initial={{ opacity: 0, y: 24 }}
            animate={inView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1], delay: 0.4 }}
          >
            <p
              className="text-[20px] lg:text-[24px] text-[#004762] leading-[32px] lg:w-[269px]"
              style={{ fontFamily: "var(--font-cal-sans)" }}
            >
              Turn your parking space into a power plant.
            </p>
            <CTAButton className="shrink-0">PARTNER WITH US NOW</CTAButton>
          </motion.div>
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════
   APP CTA BANNER
═══════════════════════════════════ */
function AppCtaSection() {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true, margin: "-60px" });

  return (
    <section className="bg-white w-full px-5 lg:px-20 py-16 lg:py-24">
      <div className="max-w-[1440px] mx-auto">
        <motion.div
          ref={ref}
          className="relative w-full h-[320px] md:h-[380px] lg:h-[442px] rounded-[32px] lg:rounded-[40px] overflow-hidden"
          initial={{ opacity: 0, y: 24 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
        >
          {/* Background */}
          <Image
            src="/images/charge/app-cta-bg.jpg"
            alt="EV charging app background"
            fill
            className="object-cover object-center"
          />

          {/* Noise overlay */}
          <div className="absolute inset-0 bg-black/50 mix-blend-plus-lighter" />

          {/* Left text content */}
          <div className="absolute inset-0 flex flex-col justify-center pl-8 lg:pl-[110px] pr-4 lg:pr-0">
            <motion.div
              className="flex flex-col gap-4 lg:gap-[19px]"
              initial={{ opacity: 0, y: 24 }}
              animate={inView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.65, ease: [0.22, 1, 0.36, 1], delay: 0.15 }}
            >
              <h2
                className="text-[40px] md:text-[60px] lg:text-[80px] font-black uppercase text-[#004762] leading-[1.17] lg:w-[512px]"
                style={{ fontFamily: "var(--font-mona-sans)" }}
              >
                FIND EV CHARGERS AND PLUG IN NOW
              </h2>

              <div className="flex flex-col gap-2">
                <p
                  className="text-[20px] lg:text-[24px] text-[#004762] leading-[32px]"
                  style={{ fontFamily: "var(--font-cal-sans)" }}
                >
                  Coming soon on...
                </p>

                {/* App store badges */}
                <div className="flex gap-4">
                  <a href="#" className="bg-black border border-[#a6a6a6] rounded-[7px] h-10 px-3 flex items-center gap-2 hover:border-white/40 transition-colors">
                    <svg viewBox="0 0 24 24" className="w-4 h-4 fill-white shrink-0"><path d="M18.71 19.5c-.83 1.24-1.71 2.45-3.05 2.47-1.34.03-1.77-.79-3.29-.79-1.53 0-2 .77-3.27.82-1.31.05-2.3-1.32-3.14-2.53C4.25 17 2.94 12.45 4.7 9.39c.87-1.52 2.43-2.48 4.12-2.51 1.28-.02 2.5.87 3.29.87.78 0 2.26-1.07 3.8-.91.65.03 2.47.26 3.64 1.98-.09.06-2.17 1.28-2.15 3.81.03 3.02 2.65 4.03 2.68 4.04-.03.07-.42 1.44-1.38 2.83M13 3.5c.73-.83 1.94-1.46 2.94-1.5.13 1.17-.34 2.35-1.04 3.19-.69.85-1.83 1.51-2.95 1.42-.15-1.15.41-2.35 1.05-3.11z"/></svg>
                    <div>
                      <p className="text-white/60 text-[8px] leading-none" style={{ fontFamily: "var(--font-instrument-sans)" }}>Download on the</p>
                      <p className="text-white text-[12px] font-semibold leading-tight" style={{ fontFamily: "var(--font-instrument-sans)" }}>App Store</p>
                    </div>
                  </a>
                  <a href="#" className="bg-black border border-[#a6a6a6] rounded-[5px] h-10 px-3 flex items-center gap-2 hover:border-white/40 transition-colors">
                    <svg viewBox="0 0 24 24" className="w-4 h-4 fill-white shrink-0"><path d="M3.18 23.76c.3.16.65.17.97.05l.1-.06 11.04-6.37-2.39-2.4-9.72 8.78zm-1.13-20.8a1.7 1.7 0 0 0-.05.42v20.24c0 .14.02.28.05.41l.06.1 11.33-11.33v-.27L2.11 2.86l-.06.1zm19.42 9.05-2.48-1.43-2.69 2.69 2.69 2.68 2.5-1.44a1.5 1.5 0 0 0 0-2.5zm-18.3 10.16 9.83-9.83-2.4-2.39L2.05 21.1l1.12 1.07z"/></svg>
                    <div>
                      <p className="text-white/60 text-[8px] leading-none" style={{ fontFamily: "var(--font-instrument-sans)" }}>Get it on</p>
                      <p className="text-white text-[12px] font-semibold leading-tight" style={{ fontFamily: "var(--font-instrument-sans)" }}>Google Play</p>
                    </div>
                  </a>
                </div>
              </div>
            </motion.div>
          </div>

          {/* Right: phone mockup */}
          <div className="absolute right-0 bottom-0 h-full w-[50%] lg:w-[700px] hidden md:block">
            {/* Hand */}
            <div className="absolute inset-0">
              <Image
                src="/images/charge/app-hand.png"
                alt=""
                fill
                className="object-contain object-bottom"
              />
            </div>
            {/* iPhone frame */}
            <div className="absolute inset-[8%_0_0_22%]">
              <Image
                src="/images/charge/iphone-16-pro.png"
                alt="Out Mobility charge EV app"
                fill
                className="object-contain object-top"
              />
            </div>
            {/* App screen content */}
            <div className="absolute inset-[14%_12%_24%_30%] rounded-[18px] overflow-hidden">
              <Image
                src="/images/charge/app-screen.png"
                alt=""
                fill
                className="object-cover object-top"
              />
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════
   ROOT EXPORT
═══════════════════════════════════ */
export default function ChargeContent() {
  return (
    <>
      <TickerBar />
      <ChargeHero />
      <DepinSection />
      <AppCtaSection />
    </>
  );
}
